[build]
publish = "public"  // default hugo build folder
command = "" // hugo build command

[context.production.environment]
HUGO_VERSION = "0.79"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
